# -*- coding: utf-8 -*-
"""MK_ii_Sms_Spam_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhRR95L_KrjsUJ6GSvhdVtCXc8afO89a
"""

import tensorflow as tf
import numpy as np
import pandas as pd


from keras import *
from keras.layers import *

from sklearn.preprocessing import *

from google.colab import drive
drive.mount('/content/drive')

"""#Importing the database

Latin1 is a character encoding that covers characters used in Western European languages and is a good choice when dealing with text data that includes special characters. If you're facing decoding issues with UTF-8, using latin1 as the encoding when reading files might help resolve those problems.
"""

df = pd.read_csv('/content/drive/MyDrive/Spam Filter Ml/datasets/data spam.csv',encoding='latin1')

#Fetches 5 rows
df.sample(5)

df['new_col'] = df[['title', 'text']].astype(str).apply(' '.join, axis=1)

exploded_df = df.explode(['title', 'text'])

# Create the desired DataFrame with separate rows
result_df = exploded_df[['text', 'type']]

print(result_df)

df.shape
#(total rows ,total cols)

"""#1. Data Cleaning
Modifying the dataset  like removing empty columns,duplicates
"""

#info about our data set
df.info()

df.sample(5)

"""Renaming columns

#Label Encoding
is a technique that is used to convert categorical columns into numerical ones so that they can be fitted by machine learning models which only take numerical data. It is an important pre-processing step in a machine-learning project.
"""

encoder = LabelEncoder()

df['target']=encoder.fit_transform(df['type'])

df.head()
#1 for not spam

"""Checking null values"""

df.isnull().sum()

"""Checking for duplicates and removing them"""

df['text'].duplicated().sum()

df=df.drop_duplicates(keep='first')

"""#2. Exploratory Data Analysis(EDA)
collecting insights about data
"""

df.head()

"""Showng percentage of spam , not spam in pie chart"""

df['target'].value_counts()

import matplotlib.pyplot as plt

plt.pie(df['target'].value_counts(),labels=['Not Spam','Spam'],autopct="%0.2f")
plt.show()

#Data is imbalannced by looking at pie

"""We count no of alphabets,words,sentences in each sms and analyze that

**punkt** tokenizer divides a text into a list of sentences by using an unsupervised algorithm to build a model for abbreviation words, collocations, and words that start sentences. It must be trained on a large collection of plaintext in the target language before it can be used.

**Changeable**
"""

# Natural Language Toolkit
import nltk
nltk.download('punkt')

"""Create 3 columns fors alphabets,words and Sentences"""

#column for no of characters in  sms
df['num_characters']=df['new_col'].apply(len)

df.head()

"""word_tokenizer breaks the sms into words"""

#no of words
df['num_words']=df['new_col'].apply(lambda x:len(nltk.word_tokenize(x)))

#len(....) counts the no of elemenents or words

#no of sentences
df['num_sentences']=df['new_col'].apply(lambda x:len(nltk.sent_tokenize(x)))

#len(....) counts the no of elemenents or words

df.head()

#Give details of the columns

df[['num_words','num_words','num_sentences']].describe()

"""Analyzing Spam (1) and not Spam(0) msgs separately"""

#Not Spam
df[df['target']==0][['num_words','num_words','num_sentences']].describe()

#Spam
df[df['target']==1][['num_words','num_words','num_sentences']].describe()

"""Using histogram to see the difference in no of sentences for Spam and not spam"""

df.head()

df.sample(10)

import seaborn as sns

#alphabets
sns.histplot(df[df['target']==0]['num_characters'])#not spam
sns.histplot(df[df['target']==1]['num_characters'],color = 'red')#spam

#words
sns.histplot(df[df['target']==0]['num_words'])#not spam
sns.histplot(df[df['target']==1]['num_words'],color = 'red')#spam

#sentences
sns.histplot(df[df['target']==0]['num_sentences'])#not spam
sns.histplot(df[df['target']==1]['num_sentences'],color = 'red')#spam

sns.pairplot(df,hue='target')

"""###Finding Correalation Coefficient
The correlation coefficient is a statistical concept which helps in establishing a relation between predicted and actual values obtained in a statistical experiment. The calculated value of the correlation coefficient explains the exactness between the predicted and actual values.
"""

sns.heatmap(df.corr(),annot=True)

"""We choose num_characters of ar 0.38

#3. Data Preprocessing


1.   LowerCase
2.   Tokenization
3.   Removing Special Caracters
4.   Removing stop words and punctuations - pronouns,is was , its etc
5.   Stemming - converting words like run running etc to onw word

####Removing stop words & punctutations func use
"""

from nltk.corpus import *
nltk.download('stopwords')
stopwords.words('english')

import string
string.punctuation

"""####Stemming func"""

from nltk.stem import *
ps = PorterStemmer()

#converts to root word
ps.stem('loving')
ps.stem('dancing')

"""####Doing all above procresses together"""

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)
  y=[]
  #Removing Special Characters ; text is a array now
  for i in text:
    if i.isalnum():
      y.append(i)

#copying values of y to text and emptying y
  text=y[:]
  y.clear()


  #Removing stop words & punctutations
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)

  text=y[:]
  y.clear()

  for i in text:
    y.append(ps.stem(i))


  return " ".join(y)

"""Demo"""

transform_text('Hey sexy buns ! Have I told you ? I adore you, loverboy. I hope you remember to thank your sister in law for those meatballs *grins* ... i love you, babe')

"""Putting transform text into a new column"""

df['transformed_text']=df['text'].apply(transform_text)

df.head()

"""####Word cloud
is a data visualization that displays the most frequent words in a text. The size of each word represents its frequency. Word clouds can be used to analyze text data and identify trends and patterns.
"""

from wordcloud import *

wc =WordCloud(width=1000,height=1000,min_font_size=10,background_color='white')

#working on spam mss
spam_wc=wc.generate(df[df['type']==1]['transformed_text'].str.cat(sep=" "))

plt.imshow(spam_wc)

#working on not spam sms
ham_wc=wc.generate(df[df['type']==0]['transformed_text'].str.cat(sep=" "))
plt.imshow(ham_wc)

"""####Top 30 words in spam
The split() method splits a string into a list.

You can specify the separator, default separator is any whitespace.
"""

spam_corpus=[]

for msg in df[df['type']==1]['transformed_text'].tolist():
  for word in msg.split():
    spam_corpus.append(word)

"""###DataFrame
is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.
"""

from collections import Counter

Counter(spam_corpus).most_common(30)

sns.barplot(
    x=pd.DataFrame(Counter(spam_corpus).most_common(30))[0],
    y=pd.DataFrame(Counter(spam_corpus).most_common(30))[1]
    )

plt.xticks(rotation='vertical')
plt.show()

"""Doing same for ham"""

ham_corpus=[]

for msg in df[df['target']==0]['transformed_text'].tolist():
  for word in msg.split():
    ham_corpus.append(word)

Counter(ham_corpus).most_common(30)

sns.barplot(
    x=pd.DataFrame(Counter(ham_corpus).most_common(30))[0],
    y=pd.DataFrame(Counter(ham_corpus).most_common(30))[1]
    )

plt.xticks(rotation='vertical')
plt.show()

df.head()

"""#4. Model Building

####For vectorizing text we start with bag of number(coursera course 2) and as input put in  naive bayes algo
"""

from sklearn.feature_extraction.text import *

import sklearn as sk

"""####TfidfVectorizer
is a tool that converts a collection of raw documents into a matrix of TF-IDF features. TF-IDF stands for Term Frequency-Inverse Document Frequency. It's a statistical method used in machine learning and information retrieval to measure the importance of a term in a document relative to a collection of documents
"""

import pickle

tfidf = pickle.load(open('/content/drive/MyDrive/Spam Filter Ml/Model 1/vectorizer.pkl', 'rb'))

#1000 words to be vectorized

cv = CountVectorizer()

"""####Supervised learning taking input X"""

#Converting sparse array to dense array

#X =cv.fit_transform(df['transformed_text']).toarray()
X=tfidf.fit_transform(df['transformed_text']).toarray()

#do compareision later

X
X.shape

"""Taking labeled output y"""

y =df['target'].values
len(y)

from sklearn.model_selection import *

#20% of the data to be used in test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

X_train

X_test

"""####Implementing naive bayees"""

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

"""####Gauss"""

gnb = GaussianNB()
mnb = pickle.load(open('/content/drive/MyDrive/Spam Filter Ml/Model 1/model.pkl', 'rb'))
bnb = BernoulliNB()

"""In machine learning, model fitting is a measurement of how well a model adapts to data that is similar to the data it was trained on.

"""

gnb.fit(X_train,y_train)
y_pred1=gnb.predict(X_test)

len(y_pred1)

len(y_test)

print("accuracy score: "+str(accuracy_score(y_test, y_pred1)))

print("confusion_matrix")
print(confusion_matrix(y_test, y_pred1))
print(" ")
print("precision_score "+str(precision_score(y_test, y_pred1,pos_label=1)))

print(len(y_test))
print(len(y_train))
X.shape

"""####Multinomial"""

mnb.fit(X_train,y_train)
y_pred2=mnb.predict(X_test)

print("accuracy score: "+str(accuracy_score(y_test, y_pred2)))

print("confusion_matrix")
print(confusion_matrix(y_test, y_pred2))
print(" ")
print("precision_score "+str(precision_score(y_test, y_pred2,pos_label=1)))

"""#### Bernouli"""

bnb.fit(X_train,y_train)
y_pred3=bnb.predict(X_test)

print("accuracy score: "+str(accuracy_score(y_test, y_pred3)))

print("confusion_matrix")
print(confusion_matrix(y_test, y_pred3))
print(" ")
print("precision_score "+str(precision_score(y_test, y_pred3,pos_label=1)))

"""We choose Multinomial Naive Bayees because prescision score is 1

Other methods used

1.   Voting clasifier
2.   Scaling
3. Weighting
4. Stacking
5. Appending no of characters to X

They were not useful for our work

#5.Linking to a website

creating a pipeline

In Python, the **pickle module** allows users to serialize and deserialize Python objects, including trained machine learning models. This means that users can save a trained model and reuse it to make predictions on new data without having to retrain the model

 Array
"""

import pickle
#wb write binary

#saving var tfdidf to ,say, file where file is object of open('vectorizer.pkl','wb')
pickle.dump(tfidf,open('vectorizer_mkii.pkl','wb'))

pickle.dump(mnb,open('model_mkii.pkl','wb'))