# -*- coding: utf-8 -*-
"""MK_iii_Character CNN Sms_Spam_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5GlOnITpPr5JfsAwQ8tspuQII4RwIAd

# 🧠 Embedding Layer Explanation:
This layer converts word indices (from the tokenizer) into dense vector representations of fixed size (embedding_dim).
 Instead of using one-hot or TF-IDF vectors, it learns better word representations during training.

 Example: The word "free" might be converted to a vector like

 [0.2, -0.1, 0.7, ..., 0.05] of length 100.
 Similar words like "win", "offer" might get embeddings that are close in vector space if they appear in similar spam contexts.


 This helps the CNN recognize patterns in text that are common in spam or ham messages.

#Imports
"""

import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
from tensorflow.keras import regularizers

from tensorflow.keras import layers
from tensorflow.keras import losses

from collections import Counter


import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from keras import *
from keras.layers import *

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
stopwords.words('english')
nltk.download('punkt_tab')

from sklearn.preprocessing import *
import pydot

!pip install nltk

from nltk.stem import *
ps = PorterStemmer()

from google.colab import drive
drive.mount('/content/drive')

"""##Importing the database

Latin1 is a character encoding that covers characters used in Western European languages and is a good choice when dealing with text data that includes special characters. If you're facing decoding issues with UTF-8, using latin1 as the encoding when reading files might help resolve those problems.
"""

df = pd.read_csv('/content/drive/MyDrive/Spam Filter Ml/datasets/spam.csv',usecols=['v1','v2'],encoding='latin1')

df.shape

df.rename(columns={'v1':'target'},inplace=True)
df.rename(columns={'v2':'text'},inplace=True)

df.shape

df.duplicated().sum()
df=df.drop_duplicates()

df.shape
#(total columns ,total rows)

df.info()

df['target']=(df.target=='spam').astype(int)

df.head()

df.info()

df.head(4)

"""####Word cloud
is a data visualization that displays the most frequent words in a text. The size of each word represents its frequency. Word clouds can be used to analyze text data and identify trends and patterns.
"""

from wordcloud import *
wc =WordCloud(width=1000,height=1000,min_font_size=10,background_color='white')
spam_wc=wc.generate(df[df['target']==1]['text'].str.cat(sep=" "))
plt.imshow(spam_wc)

ham_wc=wc.generate(df[df['target']==0]['text'].str.cat(sep=" "))
plt.imshow(ham_wc)



"""##imp check"""

def transform_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)
  y=[]
  #Removing Special Characters ; text is a array now
  for i in text:
    if i.isalnum():
      y.append(i)

#copying values of y to text and emptying y
  text=y[:]
  y.clear()


  #Removing stop words & punctutations
  for i in text:
    if i not in stopwords.words('english') and i not in string.punctuation:
      y.append(i)

  text=y[:]
  y.clear()

  for i in text:
    y.append(ps.stem(i))


  return " ".join(y)

df['text']=df['text'].apply(transform_text)

df.shape

X1=df.iloc[:, -1].values

y1=df.iloc[:,:-1].values

X1

type(X1)

print(type(y1[0]))

y1

print(y1.shape)

print(X1.shape)

"""#CNN"""

!pip install wandb

pip install --upgrade wandb

!pip install tensorflow
!pip install keras
from tensorflow.keras.preprocessing import text,sequence

from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation
from keras.layers import Embedding,LSTM
from keras.layers import Conv1D,MaxPooling1D,Flatten

import wandb
from wandb.integration.keras import WandbMetricsLogger

#from wandb.keras import WandbCallback
#from wandb.integration.keras import WandbMetricsLogger

wandb.init()

config = wandb.config
config.vocab_size=30
config.max_len=1000 #max 1000 words reviews taken max pooling
config.batch_size = 32
config.epochs = 10
config.embedding_dim = 100
config.filters = 250
config.kernel_size = 3
config.hidden_dims = 512

"""#Model build"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.20, random_state=42)

X_train = X_train.ravel()
X_test = X_test.ravel()
#
#y_train = y_train.ravel().tolist()
#y_test =y_test.ravel().tolist()
tokenizer = text.Tokenizer(num_words=config.vocab_size)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_matrix(X_train)

X_test = tokenizer.texts_to_matrix(X_test)

X_train = sequence.pad_sequences(X_train,maxlen=config.max_len)
X_test = sequence.pad_sequences(X_test,maxlen=config.max_len)

'''X_train = np.array.reshape(X_train.shape[0], 1)
X_test = np.array.reshape(X_test.shape[0], 1)'''

X_train = np.array(X_train)
X_test = np.array(X_test)
X_train_reshaped = X_train.reshape(-1, config.max_len, 1)
X_test_reshaped = X_test.reshape(-1, config.max_len, 1)

print(type(y_train))



print(X_train)

print(X_test)

X_train = np.array(X_train)

print(X_train)

type(X_train)



"""###This is main W&B model

"""

#padding = valid means 0 as it's 1D
model = Sequential()

model.add(Embedding(config.vocab_size,
                    config.embedding_dim,
                    input_length=config.max_len))
model.add(Dropout(0.5))
model.add(Conv1D(config.filters,
                 config.kernel_size,
                 padding='same',
                 activation='relu'))


model.add(MaxPooling1D())
model.add(Conv1D(config.filters,
                 config.kernel_size,
                  padding='same',
                 activation='relu'))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(config.hidden_dims,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

y_train = np.array(y_train)

Cnn_model= model.fit(X_train,y_train,
          batch_size=config.batch_size,
          epochs=config.epochs,
          validation_data=(X_test,y_test),callbacks=[WandbMetricsLogger()])

"""#EVAluation"""

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print('Test accuracy:', test_acc)

import matplotlib.pyplot as plt

# ... (rest of your code)


# Plot training & validation accuracy values
plt.plot(Cnn_model.history['accuracy'])
plt.plot(Cnn_model.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

plt.plot(Cnn_model.history['loss'])
plt.plot(Cnn_model.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper right')
plt.show()

"""#5.Linking to a website

creating a pipeline

In Python, the **pickle module** allows users to serialize and deserialize Python objects, including trained machine learning models. This means that users can save a trained model and reuse it to make predictions on new data without having to retrain the model

 Array
"""

model.save('CNN_model_h5_version.h5')

import pickle
#wb write binary

#saving var tfdidf to ,say, file where file is object of open('vectorizer.pkl','wb')
#pickle.dump(tfidf,open('vectorizer.pkl','wb'))

pickle.dump(Cnn_model,open('CNN_model.pkl','wb'))

pickle.dump(tokenizer,open('CNN_tokenizer.pkl','wb'))

"""#Esemble voting"""

import pickle

mnb = pickle.load(open('/content/drive/MyDrive/Spam Filter Ml/Model 1/model.pkl', 'rb'))

from sklearn.ensemble import VotingClassifier

eclf = VotingClassifier(estimators=[("multinomial ", mnb),("rf", model)])